apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: webapp
  labels:
    app: webapp
    version: v1
    component: backend

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - servicemonitor.yaml
  - ingress.yaml

commonLabels:
  app: webapp
  managed-by: kustomize

images:
  - name: ghcr.io/shanmeistro/devops-gitops-pipeline
    newTag: latest

namespace: default
