apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: webapp-metrics
  labels:
    app: webapp
    version: v1
    component: backend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: webapp
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      honorLabels: true
  namespaceSelector:
    matchNames:
      - default
